### ISSUE TITLE
Calling C standard library function without `std`? 🤔

### ISSUE THREAD

**Issue by ViralTaco** [AshleyRoll/squeeze#2]
Hi,
Little nitpick…
Shouldn't that line be `std::putc` given that the included header is `<cstdio>`?
https://github.com/AshleyRoll/squeeze/blob/33063d6319eb3382f488a38fa3f6829d8e292c23/example/main.cpp#L31
Or is it completely fine, and I've just been making my code less readable for years? 🤔

**Comment by AshleyRoll** [comment]
Hi, thanks for the feedback. 

I think you may be right, the technically correct options is to use `std::putc()` or `std::putchar()`

The example was not something that I was concentrating on initially, mostly working on the testing suite. I'll update the code later today/this evening.
